kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP    
  - containerPort: 15012
    hostPort: 15012
    listenAddress: "0.0.0.0"
    protocol: TCP      
  - containerPort: 15021
    hostPort: 15021
    listenAddress: "0.0.0.0"
    protocol: TCP   
  - containerPort: 15443
    hostPort: 15443
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: TCP   
  - containerPort: 30443
    hostPort: 30443
    listenAddress: "0.0.0.0"
    protocol: TCP                  
- role: worker
- role: worker